### ISSUE TITLE
World-UI Error

### ISSUE THREAD

**Issue by dmoralesgpm** [salaboy/emergency-service-drools-app#26]
The worl-ui app needs  alert-ROBBERY.png or it crashes

Thu Sep 22 16:08:38 CEST 2011 ERROR:Resource not found: data/sprites/alert-ROBBERY.png
java.lang.RuntimeException: Resource not found: data/sprites/alert-ROBBERY.png
        at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
        at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:169)
        at org.newdawn.slick.Image.<init>(Image.java:196)
        at org.newdawn.slick.SpriteSheet.<init>(SpriteSheet.java:129)
        at org.newdawn.slick.SpriteSheet.<init>(SpriteSheet.java:115)
        at com.wordpress.salaboy.emergencyservice.worldui.slick.graphicable.AnimationFactory.getEmergencySpriteSheet(AnimationFa
        at com.wordpress.salaboy.emergencyservice.worldui.slick.graphicable.AnimationFactory.getEmergencyAnimation(AnimationFact
        at com.wordpress.salaboy.emergencyservice.worldui.slick.WorldUI$1$1.execute(WorldUI.java:150)
        at com.wordpress.salaboy.emergencyservice.worldui.slick.WorldUI.render(WorldUI.java:100)
        at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:681)
        at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:408)
        at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
        at com.wordpress.salaboy.emergencyservice.worldui.slick.WorldUI.main(WorldUI.java:124)
Thu Sep 22 16:08:38 CEST 2011 ERROR:Game.render() failure - check the game code.
org.newdawn.slick.SlickException: Game.render() failure - check the game code.
        at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:684)
        at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:408)
        at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
        at com.wordpress.salaboy.emergencyservice.worldui.slick.WorldUI.main(WorldUI.java:124)

**Comment by salaboy** [comment]
Hi there, in which branch is that failing?

**Comment by dmoralesgpm** [comment]
RuleML, but i think that the master branch doesn't have the sprite too.

We will open new issues as we are testing the app. Is it nice for you?

**Comment by salaboy** [comment]
Yeah that's fine.. you can also create pull request to fix the issues if you want. This kind of issues are very easy to fix. Take a look at the V3 branch to see if that sprite is there. I suggest you to fork the project to be able to easily create pull requests :)
Cheers

**Comment by dmoralesgpm** [comment]
I haven't found the sprite (branches: v3, V3, v3 Multiinjured people, master)... 

I'm not techie at all (so i don't have a full development enviroment) but if i can fix an error i will fork the project, for sure.

Regards.

**Comment by salaboy** [comment]
Great!! I will take a look on that as soon as I can.

**Comment by dmoralesgpm** [comment]
Thanks¡

The same to car crash.

Fri Sep 23 10:52:25 CEST 2011 ERROR:Resource not found: data/sprites/alert-CAR_CRASH.png
java.lang.RuntimeException: Resource not found: data/sprites/alert-CAR_CRASH.png

**Comment by esteban-aliverti** [comment]
Car Crash and Robbery emergencies are not yet covered. This is why we don't have an icon for each of them. I suppose we could remove CRASH and ROBBERY from UI so you can never select one of those.
