### ISSUE TITLE
build failed on IncomingCallsMGMTServiceTest.doGarageTask

### ISSUE THREAD

**Issue by CedricLevasseur** [salaboy/emergency-service-drools-app#30]
mvn clean install on emergency-service-drools-app under windows/java 1.6.0_27 :

genericEmergencyProcedureTest(com.wordpress.salaboy.grid.IncomingCallsMGMTServiceTest)  Time elapsed: 20.234 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
at org.junit.Assert.fail(Assert.java:91)
    at org.junit.Assert.failNotEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:126)
    at org.junit.Assert.assertEquals(Assert.java:470)
    at org.junit.Assert.assertEquals(Assert.java:454)
    at com.wordpress.salaboy.grid.IncomingCallsMGMTServiceTest.doGarageTask(IncomingCallsMGMTServiceTest.java:280)

Any idea to resolve ?

**Comment by dmoralesgpm** [comment]
Try skipping tests: -DskipTests=true

**Comment by CedricLevasseur** [comment]
Hum hum, of course, the problem is shortcutted, but it's not a solution...

**Comment by dmoralesgpm** [comment]
of course :), only it gives you the chance to get the app running and test the use cases that don't use this code.

**Comment by salaboy** [comment]
Yes that's weird.. that's in master? I will try that here..

**Comment by salaboy** [comment]
solved on master
